services:

  frontend:
    image: "${DOCKERHUB_USERNAME}/${PROJECT_NAME}_frontend"
    volumes:
      - ../frontend/:/app/result_build/

  db:
    image: postgres:15.0-alpine
    restart: always
    depends_on:
      - frontend    
    volumes:
      - ${PROJECT_NAME}_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  
  web:
    image: "${DOCKERHUB_USERNAME}/${PROJECT_NAME}_backend"
    restart: always
    depends_on:
      - db    
    volumes:
      - ${PROJECT_NAME}_static_value:/app/static/
      - ${PROJECT_NAME}_media_value:/app/media/
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    depends_on:
      - web    
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - ${PROJECT_NAME}_static_value:/var/html/static/
      - ${PROJECT_NAME}_media_value:/var/html/media/

volumes:
  ${PROJECT_NAME}_postgres_data:   
  ${PROJECT_NAME}_static_value:
  ${PROJECT_NAME}_media_value: