services:

  frontend:
    build: ../../frontend
    volumes:
      - ../../frontend/:/app/result_build/

  db:
    image: postgres:15.0-alpine
    restart: always
    depends_on:
      - frontend    
    volumes:
      - foodgram_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../../.env
  
  web:
    build: ../../backend
    restart: always
    depends_on:
      - db    
    volumes:
      - foodgram_static_value:/app/static/
      - foodgram_media_value:/app/media/
    env_file:
      - ../../.env

  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    depends_on:
      - web    
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../../frontend/build:/usr/share/nginx/html/
      - ../../docs/:/usr/share/nginx/html/api/docs/
      - foodgram_static_value:/var/html/static/
      - foodgram_media_value:/var/html/media/

volumes:
  foodgram_postgres_data:   
  foodgram_static_value:
  foodgram_media_value:      