name: DockerHub workflow

on: [push]

jobs:

  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 12345
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install flake8 pep8-naming flake8-broken-line flake8-return
        pip install -r backend/requirements.txt
        pip install pytest-cov
    - name: Test with flake8 and tests
      env:
        DB: postgres
        DB_HOST: 127.0.0.1
        DB_PORT: 5432
        DB_PASSWORD: 12345
      run: |
        python -m flake8      
        cd backend/
        python manage.py makemigrations
        python manage.py migrate
        # python manage.py test
        pytest --cov --cov-report=xml
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}         

  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1 
      - name: Login to Docker 
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub 
        uses: docker/build-push-action@v2 
        with:
          context: backend
          push: true
          tags: alexpro1972/foodgram_backend:latest

  send_message:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
    - name: send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: ${{ github.workflow }} проекта FOODGRAM успешно выполнен!
